### ISSUE TITLE
Error docker.

### ISSUE THREAD

**Issue by bmrqs** [InstantWebP2P/iwebpp.io-controller#10]
Hello, i have this error in docker:

./appbld ./tools/genSrvKey.bash DOMAIN.xx
Build Docker image as appnet-bld:4.1
Sending build context to Docker daemon  43.83MB
Step 1/5 : FROM httpp:12.x
pull access denied for httpp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
./tools/genSrvKey.bash DOMAIN.xx ...
Unable to find image 'appnet-bld:4.1' locally
docker: Error response from daemon: pull access denied for appnet-bld, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

./apppkg
Build Docker image as appnet-srv:4.1
Sending build context to Docker daemon  43.83MB
Step 1/11 : FROM httpp:12.x
pull access denied for httpp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Build Docker image as appnet-srv:4.1
Sending build context to Docker daemon  43.83MB
Step 1/11 : FROM httpp:12.x
pull access denied for httpp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Start services ...
Unable to find image 'appnet-srv:4.1' locally
docker: Error response from daemon: pull access denied for appnet-srv, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by sequoiar** [comment]
@bmrqs need build httpp docker image firstly. https://github.com/InstantWebP2P/nodejs-httpp.git
